; language.ahk - Language switching system
; Supports English (en) and Russian (ru)

; ===LANGUAGE SYSTEM===
global CurrentLanguage := "en"  ; Default to English, will be overwritten by LoadLanguage()

; Translation maps for GUI text
class Lang {
    static EN := Map(
        ; Title and tabs
        "app_title", "Stratagem Radial Menu",
        "tab_radial", "Radial Menu",
        "tab_keybinds", "Keybinds",
        "tab_settings", "Settings",
        "tab_misc", "Misc",
        
        ; Tab 1 - Radial Menu
        "profile", "📂 Profile:",
        "new_profile", "➕ New Profile",
        "delete_profile", "❌ Delete Profile",
        "active_stratagems", "Active Stratagems:",
        "icon", "Icon",
        "name", "Name",
        "category", "Category",
        "type", "Type",
        "add", "+",
        "remove", "-",
        "up", "▲",
        "down", "▼",
        
        ; Tab 2 - Keybinds
        "keybind_profile", "📂 Keybind Profile:",
        "active_keybinds", "Active Keybinds:",
        "hotkey", "Hotkey",
        "visibility", "👁",
        "clear_hotkey", "Clear Hotkey",
        "double_click_hint", "Double-click on a stratagem to set a hotkey",
        
        ; Tab 3 - Settings
        "radial_menu_key", "Radial Menu Key:",
        "stratagem_menu", "Stratagem Menu:",
        "input_layout", "Input Layout:",
        "delays", "Delays (ms):",
        "post_menu", "Post Menu",
        "key_press", "Key Press",
        "general_hotkeys", "General Hotkeys:",
        "gui_toggle", "(GUI Toggle)",
        "suspend", "(Suspend)",
        "exit", "(Exit)",
        "profile_switch", "Profile Switch Hotkeys:",
        "next_profile", "(Next Profile)",
        "prev_profile", "(Prev Profile)",
        "gui_settings", "GUI Settings",
        "scale_size", "(Scale Size)",
        "language_choice", "(Language)",
        "radial_menu_ui", "Radial Menu UI",
        "menu_size", "(Menu Size)",
        "inner_radius", "(Inner Radius)",
        "icon_size", "(Icon Size)",
        "text_size", "(Text Size)",
        "show_text", "Show Names:",
        "camera_lock_bypass", "Camera Lock Bypass",
        "lock_cam", "Lock Camera:",
        "open_map_key", "Open Map Key:",
        "active_game_check", "Active Game Check",
        "auto_pause", "Auto-Pause:",
        "auto_close", "Auto-Close:",
        "interval", "(ms) Interval",
        "auto_language_switch", "Auto Layout Switch",
        "auto_lang", "Auto-Lang:",
        
        ; Tab 4 - Misc
        "keybind_list_overlay", "Keybind List Overlay",
        "toggle_hotkey", "Toggle Hotkey:",
        "drag_delay", "Drag Delay (ms):",
        "hold_time", "(Hold time)",
        "show_fields", "Show Fields:",
        "icon_short", "Icon",
        "key_short", "Key",
        "name_short", "Name",
        "transparency", "Transparency:",
        "assistants", "Assistants",
        "weapon_assistant", "Weapon Assistant:",
        "status_off", "○ OFF",
        "status_on", "● ON",
        "on", "ON",
        "off", "OFF",
        "weapon_assistant_on", "Weapon Assistant: ON",
        "weapon_assistant_off", "Weapon Assistant: OFF",
        "driver_assistant_on", "Driver Assistant: ON",
        "driver_assistant_off", "Driver Assistant: OFF",
        "floating_weapon", "Weapon:",
        "floating_driver", "Driver Assistant",
        "settings_btn", "Settings",
        "driver_assistant", "Driver Assistant:",
        "inventory", "Inventory",
        "quick_swap", "Quick Swap",
        "gamepad", "Gamepad",
        "enable_gamepad", "Enable:",
        "controller_type", "Controller Type:",
        "menu_button", "Menu Button:",
        "navigation_stick", "Navigation Stick:",
        "right_stick", "Right Stick",
        "left_stick", "Left Stick",
        "dpad", "D-Pad",
        "status", "Status:",
        "disabled", "○ Disabled",
        "enabled", "● Enabled",
        "gamepad_disabled", "○ Disabled",
        "gamepad_connected", "● Connected",
        "gamepad_disconnected", "○ Disconnected",
        "ocr", "Stratagem OCR",
        "ocr_hotkey", "OCR Hotkey:",
        "hold_ms", "Hold(ms)",
        "scrambler_bypass", "Scrambler Bypass:",
        "ocr_settings", "OCR Settings",
        
        ; Weapon Assistant
        "weapon_assistant_title", "Weapon Assistant",
        "weapon_mode", "Weapon Mode:",
        "cycle_mode", "Cycle Mode:",
        "macro_fire_button", "Macro Fire Button:",
        "safety_catch", "Safety Catch:",
        "reload_key", "Reload Key:",
        "interact_key", "Interact Key:",
        "timings_ms", "Delay Timings (ms):",
        "arc_thrower_charge", "Arc-Thrower:",
        "purifier_charge", "Purifier Charge:",
        "railgun_charge", "Railgun Charge:",
        "epoch_charge", "Epoch Charge:",
        "throw_delay", "Throw Delay:",
        "save_settings", "Save Settings",
        "weapon_mode_arc_thrower", "Arc-Thrower",
        "weapon_mode_purifier", "Purifier",
        "weapon_mode_railgun", "Railgun (Unsafe)",
        "weapon_mode_epoch", "Epoch",
        "weapon_mode_power_throw", "Power Throw",
        
        ; Driver Assistant
        "driver_assistant_title", "Driver Assistant",
        "forward_key", "Forward Key:",
        "backward_key", "Backward Key:",
        "exit_vehicle_key", "Exit Vehicle Key:",
        "enter_vehicle_key", "Enter Vehicle Key:",
        "enter_vehicle_on_toggle", "Enter Vehicle on DA Toggle",
        "swap_seats_key", "Swap Seats Key:",
        "gear_up_key", "Gear Up Key:",
        "gear_down_key", "Gear Down Key:",
        "forward_gear", "Forward Gear:",
        "enhanced_gear_switch", "Enhanced Gear Switch",
        "driver_stratagem_call", "Driver Stratagem Call",
        "handbrake_key", "Handbrake Key:",
        "handbrake_on_exit", "Handbrake on Exit",
        "key_press_delay_da", "Key Press Delay (ms):",
        "show_in_list", "Show in Floating List",
        
        ; Inventory Manager
        "inventory_manager_title", "Inventory Manager",
        "drop_backpack", "Drop Backpack ↖:",
        "drop_weapon", "Drop Weapon ↗:",
        "drop_suitcase", "Drop Suitcase ↙:",
        "drop_samples", "Drop Samples ↘:",
        "inventory_key", "Inventory Key:",
        "hold_key", "Hold Key:",
        "release_key", "Release Key:",
        "mouse_sensitivity", "Mouse Sensitivity:",
        "multiplier", "Multiplier:",
        
        ; Weapon Quick Switch
        "weapon_swap_title", "Weapon Swap",
        "quick_switch_key", "Quick Switch Key:",
        "track_weapon_slots", "Track Weapon Slots:",
        "slot_label", "Slot",
        "switch_info", "The switch key swaps between current and last used weapon slot.",
        
        ; OCR Settings
        "ocr_settings_title", "OCR Settings (Base Values for 1440p)",
        "general_settings", "General Settings",
        "detected_resolution", "Detected Resolution:",
        "use_custom_resolution", "Use custom resolution",
        "width", "Width:",
        "height", "Height:",
        "max_rows", "MaxRows:",
        "max_arrows_per_row", "MaxArrowsPerRow:",
        "menu_open_delay", "Menu open delay (ms):",
        "hud_scale", "The in-game HUD Scale:",
        "debug_mode_visualization", "Debug mode (visualization)",
        "arrow_position", "Arrow Position (center)",
        "start_x", "Start X:",
        "start_y", "Start Y:",
        "arrow_step_x", "ArrowStepX:",
        "arrow_step_y", "ArrowStepY:",
        "icon_position", "Icon Position (frame)",
        "icon_size_ocr", "Icon Size:",
        "vertical_step", "Vertical Step:",
        "arrow_detection_method", "Arrow Detection Method",
        "detection_method", "Detection Method:",
        "color_detection_ddl", "Color",
        "shape_detection_ddl", "Shape (Beta)",
        "color_detection", "Color Detection",
        "arrow_color_rgb", "ArrowColor (RGB):",
        "color_tolerance", "ColorTolerance(0-255):",
        "extract_color_tol", "ExtractColorTol(0-255):",
        "arrow_check_distance", "ArrowCheckDistance(px):",
        "arrow_edge_strip_size", "ArrowEdgeStripSize(px):",
        "arrow_center_stability", "ArrowCenterStability:",
        "min_edge_matches", "MinEdgeMatches(px):",
        "template_label", "Template:",
        "current_temp", "Current",
        "fault_tolerance", "Fault Tolerance:",
        "fault_tolerance_steps", "Scan Steps:",
        "shape_detection", "Shape Detection",
        "use_custom_shape_template_checkbox", "Use custom shape template",
        "shape_template_resolution", "Shape Template Resolution:",
        "gray2two_patterns", "Gray2Two patterns",
        "graydiff2two_patterns", "GrayDiff2Two patterns",
        "apply", "Apply",
        "exclusion_list", "Exclusion List",
        "reset", "Reset",
        "checked_stratagems_excluded", "Checked stratagems will be excluded from OCR profile updates",
        "save", "Save",
        "clear", "Clear",
        "ocr_excluded_stratagems", "OCR Excluded Stratagems",
        "exclusions_saved", "Exclusions saved",
        "exclusions_cleared", "Exclusions cleared",
        "settings_saved", "Settings saved",
        "settings_reset_defaults", "Settings reset to defaults",
        
        ; Tooltips
        "tooltip_scrambler_no_stratagems", "Scrambler: No stratagems detected!",
        "tooltip_no_stratagems_profile", "No stratagems in active profile!",
        "tooltip_keybind_profile", "Keybind Profile:",
        "tooltip_profile", "Profile:",
        "tooltip_scrambler_no_sequence_slot", "Scrambler: No sequence for slot",
        "tooltip_ocr_scrambler_bypass", "OCR Scrambler Bypass:",
        "tooltip_ocr_no_stratagems", "OCR: no stratagems found",
        "tooltip_ocr_profile_loaded", "OCR profile loaded:",
        "tooltip_ocr_objective_cant_read", "OCR objective: can't read sequence",
        "tooltip_ocr_bypass_cant_read", "OCR bypass: can't read sequence",
        "tooltip_game_closing", "Game closed. Exiting in",
        "tooltip_status", "Status:",
        
        ; Selection popup
        "select_stratagem", "Select Stratagem",
        "search", "Search:",
        "favorites", "★",
        "add_selected", "Add Selected",
        "double_click_favorite", "Double-click a stratagem to mark it as favorite (★)",
        "select_all_hint", "Ctrl+A to select all",
        
        ; Input layouts
        "arrows", "Arrows",
        "wasd", "WASD",
        "custom", "[Custom]",
        
        ; Radial menu key modes
        "hold", "Hold",
        "toggle", "Toggle",
        
        ; Menu input types
        "tap", "Tap",
        "double_tap", "Double Tap",
        "press", "Press",
        "long_press", "Long Press",
        "hold_input", "Hold",
        
        ; Controller types
        "xbox", "Xbox",
        "playstation", "PlayStation",
        
        ; Tray menu
        "tray_show", "Show",
        "tray_suspend", "Suspend",
        "tray_reload", "Reload",
        "tray_exit", "Exit",
        
        ; Additional UI strings
        "save", "Save",
        "cancel", "Cancel",
        "press_key_for", "Press a key for:",
        "current", "Current",
        "set_hotkey", "Set Hotkey",
        "custom_keys", "Custom Keys",
        "up_key", "Up Key:",
        "down_key", "Down Key:",
        "left_key", "Left Key:",
        "right_key", "Right Key:",
        "new_profile_title", "New Profile",
        "new_keybind_profile_title", "New Keybind Profile",
        "enter_profile_name", "Enter a name for the new profile:",
        "profile_created", "Profile Created",
        "cannot_delete_default", "Cannot delete the Default profile!",
        "confirm_delete", "Confirm Delete",
        "delete_profile_confirm", "Delete profile '",
        "profile_deleted", "Profile deleted. Switched to:",
        "please_select_stratagem", "Please select a stratagem.",
        "no_bindings", "No bindings",
        "custom_keys_saved", "Custom keys saved!",
        "add_to_keybinds", "Add to Keybinds",
        "no_stratagem_selected", "Please select a stratagem.",
        "not_set", "Not Set",
        "radial_menu_key_help", "Radial Menu Key",
        "show_hide_gui_help", "Show/Hide GUI",
        "floating_list_help", "Floating List Overlay (Hold to drag)",
        "ocr_scan_help", "OCR Stratagem Scan",
        "scrambler_bypass_help", "Scrambler Bypass Toggle",
        "interval_help", "ms Interval",
        "hotkey_reserved", "Cannot use this hotkey!",
        "already_used_for", "is already used for:",
        "please_choose_different", "Please choose a different hotkey.",
        "hotkey_reserved_title", "Hotkey Reserved",
        "reserved_radial_menu_key", "Radial Menu Key",
        "reserved_gui_toggle", "GUI Toggle",
        "reserved_suspend", "Suspend",
        "reserved_exit", "Exit",
        "reserved_next_profile", "Next Profile",
        "reserved_prev_profile", "Prev Profile",
        "reserved_keybind_list_overlay", "Keybind List Overlay",
        "reserved_ocr_scan", "OCR Scan",
        "reserved_ocr_bypass_toggle", "OCR Scrambler Bypass Toggle",
        "reserved_weapon_assistant_toggle", "Weapon Assistant Toggle",
        "reserved_weapon_assistant_fire", "Weapon Assistant Fire",
        "reserved_weapon_mode_cycle", "Weapon Mode Cycle",
        "reserved_weapon_safety", "Weapon Safety",
        "reserved_driver_assistant_toggle", "Driver Assistant Toggle",
        "invalid_hotkey", "Invalid hotkey:",
        "profile_create_success", "Profile created:",
        "keybind_profile_create_success", "Keybind profile created:",
        "profile_delete_success", "Profile deleted. Switched to:",
        "keybind_profile_delete_success", "Keybind profile deleted. Switched to:",
        "delete_confirm_title", "Confirm Delete",
        "error_title", "Error",
        "profile_created_title", "Profile Created",
        "profile_deleted_title", "Profile Deleted",
        
        ; Profile dialogs
        "new_profile_title", "New Profile",
        "new_keybind_profile_title", "New Keybind Profile",
        "enter_profile_name", "Enter a name for the new profile:",
        "confirm_delete", "Confirm Delete",
        "delete_profile_confirm", "Delete profile '",
        "cannot_delete_default", "Cannot delete the Default profile!",
        "exclusions_saved", "Exclusions saved",
        "exclusions_cleared", "Exclusions cleared",
        "settings_saved", "Settings saved",
        "settings_reset_defaults", "Settings reset to defaults",
        "tooltip_scrambler_no_stratagems", "Scrambler: No stratagems detected!",
        "tooltip_no_stratagems_profile", "No stratagems in active profile!",
        "tooltip_keybind_profile", "Keybind Profile:",
        "tooltip_profile", "Profile:",
        "tooltip_scrambler_no_sequence_slot", "Scrambler: No sequence for slot",
        "tooltip_ocr_scrambler_bypass", "OCR Scrambler Bypass:",
        "tooltip_ocr_no_stratagems", "OCR: no stratagems found",
        "tooltip_ocr_profile_loaded", "OCR profile loaded:",
        "tooltip_ocr_objective_cant_read", "OCR objective: can't read sequence",
        "tooltip_ocr_bypass_cant_read", "OCR bypass: can't read sequence",
        "tooltip_game_closing", "Game closed. Exiting in",
        "tooltip_status", "Status:",
        "tooltip_weapon_mode", "Weapon Mode:",
        "status_suspended", "Suspended",
        "status_autopause", "Auto-Pause",
        "status_active", "Active",

        ; Stratagem Editor
        "editor_title", "Stratagem Editor",
        "search", "Search:",
        "new_stratagem", "New",
        "edit_stratagem", "Edit",
        "delete_stratagem", "Delete",
        "select_to_edit", "Please select a stratagem to edit.",
        "cannot_edit_categories", "Cannot edit categories.",
        "stratagem_not_found", "Stratagem not found.",
        "select_to_delete", "Please select a stratagem to delete.",
        "confirm_delete", "Confirm Delete",
        "delete_confirm_msg", "Are you sure you want to delete '",
        "id_label", "ID:",
        "name_label", "Name:",
        "category_label", "Category:",
        "sequence_label", "Sequence:",
        "sequence_example", "Example: Up, Down, Left, Right",
        "save", "Save",
        "cancel", "Cancel",
        "all_fields_required", "All fields are required.",
        "id_already_exists", "A stratagem with this ID already exists!",
        "invalid_sequence", "Invalid sequence. Use: Up, Down, Left, Right",
        "cat_offensive", "Offensive Stratagems",
        "cat_supply", "Supply Stratagems",
        "cat_defensive", "Defensive Stratagems",
        "cat_mission", "Mission Stratagems",
        "clear_button_text", "Clear",
        
        ; Gamepad capture popup
        "capture_gamepad_button", "Capture Gamepad Button",
        "capture_ocr_gamepad_button", "Capture OCR Gamepad Button",
        "capture_bypass_button", "Capture Bypass Button",
        "press_gamepad_button", "Press a button on your gamepad...",
        
        ; OCR Scan popup messages
        "ocr_no_stratagems_found", "No stratagems found!",
        "ocr_scan_result", "Scan Result",
        "ocr_all_excluded", "All detected stratagems (including required tail entries) are in the exclusion list. Nothing was written to profile.",
        "ocr_no_usable", "No usable stratagems found and all required tail entries are excluded. Nothing was written to profile.",
        "ocr_stratagems_found", "Stratagems found: ",
        "ocr_written_to_profile", "Written to profile: ",
        "ocr_row_prefix", " (row ",
        "ocr_row_suffix", ")",
        "ocr_detected_arrow_color", "Detected Arrow Color (1st arrow of 2nd row):",
        "ocr_unknown", "Unknown",
        "ocr_best_match", " (best match)",
        "ocr_additional_stratagems", "Additional stratagems added to profile:"
    )
    
    static RU := Map(
        ; Title and tabs
        "app_title", "Радиальное Меню Стратагем",
        "tab_radial", "Радиальное меню",
        "tab_keybinds", "Привязки",
        "tab_settings", "Настройки",
        "tab_misc", "Разное",
        
        ; Tab 1 - Radial Menu
        "profile", "📂 Профиль:",
        "new_profile", "➕ Новый профиль",
        "delete_profile", "❌ Удалить профиль",
        "active_stratagems", "Активные Стратагемы:",
        "icon", "Иконка",
        "name", "Название",
        "category", "Категория",
        "type", "Тип",
        "add", "+",
        "remove", "-",
        "up", "▲",
        "down", "▼",
        
        ; Tab 2 - Keybinds
        "keybind_profile", "📂 Профиль Привязок:",
        "active_keybinds", "Активные Привязки:",
        "hotkey", "Клавиша",
        "visibility", "👁",
        "clear_hotkey", "Очистить клавишу",
        "double_click_hint", "Дважды щелкните по стратагеме для установки клавиши",
        
        ; Tab 3 - Settings
        "radial_menu_key", "Радиальное Меню:",
        "stratagem_menu", "Меню Стратагем:",
        "input_layout", "Раскладка Ввода:",
        "delays", "Задержки (мс):",
        "post_menu", "После кл. меню",
        "key_press", "Нажатие клавиш",
        "general_hotkeys", "Основные Клавиши:",
        "gui_toggle", "(Показать/Скрыть)",
        "suspend", "(Пауза)",
        "exit", "(Выход)",
        "profile_switch", "Переключение Профиля:",
        "next_profile", "(След. профиль)",
        "prev_profile", "(Пред. профиль)",
        "gui_settings", "Настройки GUI",
        "scale_size", "(Масштаб)",
        "language_choice", "(Язык)",
        "radial_menu_ui", "Радиальное Меню GUI",
        "menu_size", "(Размер меню)",
        "inner_radius", "(Внутр. радиус)",
        "icon_size", "(Разм. иконок)",
        "text_size", "(Разм. текста)",
        "show_text", "Показ текста:",
        "camera_lock_bypass", "Блокировка Камеры",
        "lock_cam", "Блок. камеру:",
        "open_map_key", "Клавиша карты:",
        "active_game_check", "Проверка Игры",
        "auto_pause", "Авто-пауза:",
        "auto_close", "Авто-закрытие:",
        "interval", "(мс) Интервал",
        "auto_language_switch", "Автосмена Раскладки",
        "auto_lang", "Авто-язык:",
        
        ; Tab 4 - Misc
        "keybind_list_overlay", "Плавающий Список",
        "toggle_hotkey", "Список Привязок:",
        "drag_delay", "Перетаскивание:",
        "hold_time", "(мс) удержания",
        "show_fields", "Показывать Поля:",
        "icon_short", "Ик.",
        "key_short", "Кл.",
        "name_short", "Текст",
        "transparency", "Прозрачность:",
        "assistants", "Ассистенты",
        "weapon_assistant", "Ассистент Оружия:",
        "status_off", "○ ВЫКЛ",
        "status_on", "● ВКЛ",
        "on", "ВКЛ",
        "off", "ВЫКЛ",
        "weapon_assistant_on", "Ассистент Оружия: ВКЛ",
        "weapon_assistant_off", "Ассистент Оружия: ВЫКЛ",
        "driver_assistant_on", "Ассистент Водителя: ВКЛ",
        "driver_assistant_off", "Ассистент Водителя: ВЫКЛ",
        "floating_weapon", "Оружие:",
        "floating_driver", "Ассистент Водителя",
        "settings_btn", "Настройки",
        "driver_assistant", "Ассистент Водителя:",
        "inventory", "Инвентарь",
        "quick_swap", "Быстрая Смена",
        "gamepad", "Геймпад",
        "enable_gamepad", "Включить:",
        "controller_type", "Тип контроллера:",
        "menu_button", "Кнопка меню:",
        "navigation_stick", "Стик навигации:",
        "right_stick", "Правый стик",
        "left_stick", "Левый стик",
        "dpad", "Крестовина",
        "status", "Статус:",
        "disabled", "○ Отключен",
        "enabled", "● Включен",
        "ocr", "Распознавание Стратагем",
        "ocr_hotkey", "Клавиша OCR:",
        "hold_ms", "Удержание(мс)",
        "scrambler_bypass", "Обход Искажений:",
        "ocr_settings", "Настройки OCR",
        
        ; Weapon Assistant
        "weapon_assistant_title", "Ассистент Оружия",
        "weapon_mode", "Режим оружия:",
        "cycle_mode", "Смена режима:",
        "macro_fire_button", "Макрос выстрела:",
        "safety_catch", "Предохранитель:",
        "reload_key", "Кл. перезарядки:",
        "interact_key", "Кл. взаимодействия:",
        "timings_ms", "Тайминги Задержки (мс):",
        "arc_thrower_charge", "Дуговой:",
        "purifier_charge", "Очиститель:",
        "railgun_charge", "Рельсотрон:",
        "epoch_charge", "Эпоха:",
        "throw_delay", "Перед броском:",
        "save_settings", "Сохранить настройки",
        "weapon_mode_arc_thrower", "Дуговой Метатель",
        "weapon_mode_purifier", "Очиститель",
        "weapon_mode_railgun", "Рельсотрон",
        "weapon_mode_epoch", "Эпоха",
        "weapon_mode_power_throw", "Сильный Бросок",
        
        ; Driver Assistant
        "driver_assistant_title", "Ассистент Водителя",
        "forward_key", "Вперед:",
        "backward_key", "Назад:",
        "exit_vehicle_key", "Выход из транспорта:",
        "enter_vehicle_key", "Вход в транспорт:",
        "enter_vehicle_on_toggle", "Вход в транспорт при включении АВ",
        "swap_seats_key", "Смена места:",
        "gear_up_key", "Повысить передачу:",
        "gear_down_key", "Понизить передачу:",
        "forward_gear", "Передняя передача:",
        "enhanced_gear_switch", "Улучшенное переключение",
        "driver_stratagem_call", "Вызов стратагем",
        "handbrake_key", "Ручной тормоз:",
        "handbrake_on_exit", "Ручной тормоз при выходе",
        "key_press_delay_da", "Задержка нажатий (мс):",
        "show_in_list", "Показывать в плавающем списке",
        
        ; Inventory Manager
        "inventory_manager_title", "Менеджер Инвентаря",
        "drop_backpack", "Выбросить рюкзак ↖:",
        "drop_weapon", "Выбросить оружие ↗:",
        "drop_suitcase", "Выбросить чемодан ↙:",
        "drop_samples", "Выбросить пробы ↘:",
        "inventory_key", "Клавиша инвентаря:",
        "hold_key", "Удержание:",
        "release_key", "Выдержка:",
        "mouse_sensitivity", "Чувствительность мыши:",
        "multiplier", "Множитель:",
        
        ; Weapon Quick Switch
        "weapon_swap_title", "Быстрая Смена Оружия",
        "quick_switch_key", "Клавиша переключения:",
        "track_weapon_slots", "Отслеживать слоты:",
        "slot_label", "Слот",
        "switch_info", "Клавиша переключения меняет текущий и предыдущий слот оружия.",
        
        ; OCR Settings
        "ocr_settings_title", "Настройки OCR (Базовые значения для 1440p)",
        "general_settings", "Основные настройки",
        "detected_resolution", "Обнаруженное разрешение:",
        "use_custom_resolution", "Использовать другое разрешение",
        "width", "Ширина:",
        "height", "Высота:",
        "max_rows", "Макс. строк:",
        "max_arrows_per_row", "Макс. стрелок в строке:",
        "menu_open_delay", "Задержка меню (мс):",
        "hud_scale", "Масштаб HUD в игре:",
        "debug_mode_visualization", "Режим отладки (визуализация)",
        "arrow_position", "Позиция стрелок (центр)",
        "start_x", "Начало X:",
        "start_y", "Начало Y:",
        "arrow_step_x", "Горизонтальный шаг:",
        "arrow_step_y", "Вертикальный шаг:",
        "icon_position", "Позиция иконок (рамка)",
        "icon_size_ocr", "Размер иконок:",
        "vertical_step", "Вертикальный шаг:",
        "arrow_detection_method", "Метод обнаружения стрелок",
        "detection_method", "Метод обнаружения:",
        "color_detection_ddl", "По цвету",
        "shape_detection_ddl", "По форме (Бета)",
        "color_detection", "Обнаружение по цвету",
        "arrow_color_rgb", "Цвет стрелки (RGB):",
        "color_tolerance", "Допуск цвета(0-255):",
        "extract_color_tol", "Извлеченный цвет:",
        "arrow_center_stability", "Стабильность центра:",
        "arrow_check_distance", "Дистанция проверки:",
        "arrow_edge_strip_size", "Краевая полоса(пиксл):",
        "min_edge_matches", "Мин. совпад. краевой:",
        "template_label", "Шаблон:",
        "current_temp", "Текущий",
        "fault_tolerance", "Допуск ошибок:",
        "fault_tolerance_steps", "Шаги поиска:",
        "shape_detection", "Обнаружение по форме",
        "use_custom_shape_template_checkbox", "Использовать другой шаблон",
        "shape_template_resolution", "Разрешение шаблона:",
        "gray2two_patterns", "Шаблоны Gray2Two",
        "graydiff2two_patterns", "Шаблоны GrayDiff2Two",
        "apply", "Применить",
        "exclusion_list", "Список исключений",
        "reset", "Сбросить",
        "checked_stratagems_excluded", "Отмеченные стратагемы исключаются из обновления OCR профиля",
        "save", "Сохранить",
        "clear", "Очистить",
        "ocr_excluded_stratagems", "Исключенные стратагемы OCR",
        
        ; Selection popup
        "select_stratagem", "Выбор стратагем",
        "search", "Поиск:",
        "favorites", "★",
        "add_selected", "Добавить выбранные",
        "double_click_favorite", "Дважды щелкните по стратагеме чтобы добавить в избранное (★)",
        "select_all_hint", "Ctrl+A для выбора всех",
        
        ; Input layouts
        "arrows", "Стрелки",
        "wasd", "WASD",
        "custom", "[Своя]",
        
        ; Radial menu key modes
        "hold", "Удержание",
        "toggle", "Переключение",
        
        ; Menu input types
        "tap", "Клик",
        "double_tap", "Двойной клик",
        "press", "Нажатие",
        "long_press", "Долгое нажатие",
        "hold_input", "Удержание",
        
        ; Controller types
        "xbox", "Xbox",
        "playstation", "PlayStation",
        
        ; Tray menu
        "tray_show", "Показать",
        "tray_suspend", "Пауза",
        "tray_reload", "Перезапустить",
        "tray_exit", "Выход",
        
        ; Additional UI strings
        "save", "Сохранить",
        "cancel", "Отмена",
        "press_key_for", "Нажмите клавишу для:",
        "current", "Текущая",
        "set_hotkey", "Назначить клавишу",
        "custom_keys", "Свои клавиши",
        "up_key", "Вверх:",
        "down_key", "Вниз:",
        "left_key", "Влево:",
        "right_key", "Вправо:",
        "new_profile_title", "Новый профиль",
        "new_keybind_profile_title", "Новый профиль привязок",
        "enter_profile_name", "Введите имя для нового профиля:",
        "profile_created", "Профиль создан",
        "cannot_delete_default", "Нельзя удалить профиль Default!",
        "confirm_delete", "Подтвердить удаление",
        "delete_profile_confirm", "Удалить профиль '",
        "profile_deleted", "Профиль удален. Переключено на:",
        "please_select_stratagem", "Пожалуйста, выберите стратагему.",
        "no_bindings", "Нет привязок",
        "custom_keys_saved", "Клавиши сохранены!",
        "add_to_keybinds", "Добавить в привязки",
        "no_stratagem_selected", "Пожалуйста, выберите стратагему.",
        "not_set", "Не задана",
        "radial_menu_key_help", "Радиальное Меню",
        "show_hide_gui_help", "Показать/Скрыть GUI",
        "floating_list_help", "Плавающий Список (Удерживать для перетаскивания)",
        "ocr_scan_help", "Распознать Стратагемы",
        "scrambler_bypass_help", "Обход Искажений",
        "interval_help", "мс Интервал",
        "hotkey_reserved", "Нельзя использовать эту клавишу!",
        "already_used_for", "уже используется для:",
        "please_choose_different", "Пожалуйста, выберите другую клавишу.",
        "hotkey_reserved_title", "Клавиша занята",
        "reserved_radial_menu_key", "Радиальное Меню",
        "reserved_gui_toggle", "Показать/Скрыть GUI",
        "reserved_suspend", "Пауза",
        "reserved_exit", "Выход",
        "reserved_next_profile", "Следующий профиль",
        "reserved_prev_profile", "Предыдущий профиль",
        "reserved_keybind_list_overlay", "Плавающий Список",
        "reserved_ocr_scan", "Распознавание Стратагем OCR",
        "reserved_ocr_bypass_toggle", "Обход Искажений OCR",
        "reserved_weapon_assistant_toggle", "Переключение Ассистента Оружия",
        "reserved_weapon_assistant_fire", "Огонь Ассистента Оружия",
        "reserved_weapon_mode_cycle", "Смена режима оружия",
        "reserved_weapon_safety", "Предохранитель",
        "reserved_driver_assistant_toggle", "Переключение Ассистента Водителя",
        "invalid_hotkey", "Некорректная клавиша:",
        "profile_create_success", "Профиль создан:",
        "keybind_profile_create_success", "Профиль привязок создан:",
        "profile_delete_success", "Профиль удален. Переключено на:",
        "keybind_profile_delete_success", "Профиль привязок удален. Переключено на:",
        "delete_confirm_title", "Подтвердить удаление",
        "error_title", "Ошибка",
        "profile_created_title", "Профиль создан",
        "profile_deleted_title", "Профиль удален",
        
        ; Profile dialogs
        "new_profile_title", "Новый профиль",
        "new_keybind_profile_title", "Новый профиль привязок",
        "enter_profile_name", "Введите имя для нового профиля:",
        "confirm_delete", "Подтвердить удаление",
        "delete_profile_confirm", "Удалить профиль '",
        "cannot_delete_default", "Нельзя удалить профиль Default!",
        "tooltip_weapon_mode", "Режим оружия:",
        "exclusions_saved", "Исключения сохранены",
        "exclusions_cleared", "Исключения очищены",
        "settings_saved", "Настройки сохранены",
        "settings_reset_defaults", "Настройки сброшены до стандартных",
        "status_suspended", "Приостановлен",
        "status_autopause", "Автопауза",
        "status_active", "Активен",
        "gamepad_disabled", "○ Отключен",
        "gamepad_connected", "● Подключен",
        "gamepad_disconnected", "○ Отсоединен",
        
        ; Tooltips
        "tooltip_scrambler_no_stratagems", "Скамблер: Стратагемы не обнаружены!",
        "tooltip_no_stratagems_profile", "Нет стратагем в активном профиле!",
        "tooltip_keybind_profile", "Профиль привязок:",
        "tooltip_profile", "Профиль:",
        "tooltip_scrambler_no_sequence_slot", "Скамблер: Нет последовательности для слота",
        "tooltip_ocr_scrambler_bypass", "Обход Искажений OCR:",
        "tooltip_ocr_no_stratagems", "OCR: стратагемы не найдены",
        "tooltip_ocr_profile_loaded", "OCR профиль загружен:",
        "tooltip_ocr_objective_cant_read", "OCR Миссии: не удалось прочитать последовательность",
        "tooltip_ocr_bypass_cant_read", "Обход Искажений OCR: не удалось прочитать последовательность",
        "tooltip_game_closing", "Игра закрыта. Выход через",
        "tooltip_status", "Статус:",
        
        ; Stratagem Editor
        "editor_title", "Редактор Стратагем",
        "search", "Поиск:",
        "new_stratagem", "Новая",
        "edit_stratagem", "Изменить",
        "delete_stratagem", "Удалить",
        "select_to_edit", "Пожалуйста, выберите стратагему для редактирования.",
        "cannot_edit_categories", "Нельзя редактировать категории.",
        "stratagem_not_found", "Стратагема не найдена.",
        "select_to_delete", "Пожалуйста, выберите стратагему для удаления.",
        "confirm_delete", "Подтвердить удаление",
        "delete_confirm_msg", "Вы уверены, что хотите удалить '",
        "id_label", "ID:",
        "name_label", "Название:",
        "category_label", "Категория:",
        "sequence_label", "Секвенция:",
        "sequence_example", "Пример: Вверх, Вниз, Влево, Вправо",
        "save", "Сохранить",
        "cancel", "Отмена",
        "all_fields_required", "Все поля обязательны.",
        "id_already_exists", "Стратагема с таким ID уже существует!",
        "invalid_sequence", "Некорректная последовательность. Используйте: Вверх, Вниз, Влево, Вправо",
        "cat_offensive", "Стратагемы Наступления",
        "cat_supply", "Стратагемы Снабжения",
        "cat_defensive", "Стратагемы Обороны",
        "cat_mission", "Стратагемы Задания",
        "clear_button_text", "Очистить",
        
        ; Gamepad capture popup
        "capture_gamepad_button", "Захват кнопки геймпада",
        "capture_ocr_gamepad_button", "Захват кнопки OCR геймпада",
        "capture_bypass_button", "Захват кнопки обхода",
        "press_gamepad_button", "Нажмите кнопку на геймпаде...",
        
        ; OCR Scan popup messages
        "ocr_no_stratagems_found", "Стратагемы не найдены!",
        "ocr_scan_result", "Результат сканирования",
        "ocr_all_excluded", "Все обнаруженные стратагемы (включая обязательные) находятся в списке исключений. Ничего не записано в профиль.",
        "ocr_no_usable", "Не найдено подходящих стратагем, и все обязательные записи исключены. Ничего не записано в профиль.",
        "ocr_stratagems_found", "Стратагем найдено: ",
        "ocr_written_to_profile", "Записано в профиль: ",
        "ocr_row_prefix", " (строка ",
        "ocr_row_suffix", ")",
        "ocr_detected_arrow_color", "Обнаруженный цвет стрелки (1-я стрелка 2-го ряда):",
        "ocr_unknown", "Неизвестно",
        "ocr_best_match", " (совпад.)",
        "ocr_additional_stratagems", "Дополнительные стратагемы, добавленные в профиль:"
    )
    
    ; Get translation for a key
    static Get(key) {
        global CurrentLanguage
        ; Default to English if language hasn't been loaded yet
        lang := (IsSet(CurrentLanguage) && CurrentLanguage = "ru") ? "ru" : "en"
        langMap := (lang = "ru") ? this.RU : this.EN
        if langMap.Has(key)
            return langMap[key]
        return key
    }
    
    ; Switch language
    static Set(lang) {
        global CurrentLanguage
        CurrentLanguage := lang
    }
    
    ; Get current language
    static GetCurrent() {
        global CurrentLanguage
        return CurrentLanguage
    }
}

; Load language from settings
LoadLanguage() {
    global CurrentLanguage, IniPath
    try {
        CurrentLanguage := IniRead(IniPath, "Settings", "Language", "en")
        if (CurrentLanguage != "en" && CurrentLanguage != "ru")
            CurrentLanguage := "en"
    } catch {
        CurrentLanguage := "en"
    }
}

; Save language to settings
SaveLanguage() {
    global CurrentLanguage, IniPath
    IniWrite(CurrentLanguage, IniPath, "Settings", "Language")
}

; Get stratagems file path based on language
GetStratagemsPath() {
    global CurrentLanguage, A_ScriptDir
    ; Default to English if language hasn't been loaded yet
    lang := (IsSet(CurrentLanguage) && CurrentLanguage = "ru") ? "ru" : "en"
    if (lang = "ru") {
        ; Check if Russian stratagems file exists in current directory
        ruPath := A_ScriptDir "\Config\stratagems(ru).ini"
        if FileExist(ruPath)
            return ruPath
    }
    return A_ScriptDir "\Config\stratagems.ini"
}